/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cryptoProject.GUIFrames;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Priyansu
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePage_Panel = new javax.swing.JPanel();
        cryptFunct_Label_HomePage_Panel = new javax.swing.JLabel();
        ExitButton_Homepage_Panel = new javax.swing.JButton();
        contentPanel_HomePage_Panel = new javax.swing.JPanel();
        text_EnDe_Label_Content_Panel_Homepage_Panel = new javax.swing.JLabel();
        file_EnDe_Label_Content_Panel_Homepage_Panel = new javax.swing.JLabel();
        image_EnDe_Label_Content_Panel_Homepage_Panel = new javax.swing.JLabel();
        visualCryptograpphy_Label_Content_Panel_Homepage_Panel = new javax.swing.JLabel();
        steganography_Label_Content_Panel_Homepage_Panel = new javax.swing.JLabel();
        bodyPanel_HomePage_Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CryptFunct");
        setBackground(new java.awt.Color(0, 0, 30));
        setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(230, 90));
        setMaximumSize(new java.awt.Dimension(929, 557));
        setMinimumSize(new java.awt.Dimension(929, 557));
        setName("homeFrame"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(929, 557));
        setResizable(false);
        setSize(new java.awt.Dimension(929, 557));

        homePage_Panel.setVisible(true);
        homePage_Panel.setBackground(new java.awt.Color(25, 25, 25));
        homePage_Panel.setMaximumSize(new java.awt.Dimension(929, 557));
        homePage_Panel.setMinimumSize(new java.awt.Dimension(929, 557));

        cryptFunct_Label_HomePage_Panel.setBackground(new java.awt.Color(25, 25, 25));
        cryptFunct_Label_HomePage_Panel.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        cryptFunct_Label_HomePage_Panel.setForeground(new java.awt.Color(102, 255, 255));
        cryptFunct_Label_HomePage_Panel.setText("Crypt Funct");
        cryptFunct_Label_HomePage_Panel.setToolTipText("- Developed by PRIYANSU BISHT");
        cryptFunct_Label_HomePage_Panel.setOpaque(true);

        ExitButton_Homepage_Panel.setBackground(new java.awt.Color(25, 25, 25));
        ExitButton_Homepage_Panel.setForeground(new java.awt.Color(225, 217, 154));
        ExitButton_Homepage_Panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/cross_darkgray.png"))); // NOI18N
        ExitButton_Homepage_Panel.setToolTipText("EXIT");
        ExitButton_Homepage_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        ExitButton_Homepage_Panel.setBorderPainted(false);
        ExitButton_Homepage_Panel.setContentAreaFilled(false);
        ExitButton_Homepage_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitButton_Homepage_Panel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ExitButton_Homepage_Panel.setMaximumSize(new java.awt.Dimension(50, 50));
        ExitButton_Homepage_Panel.setMinimumSize(new java.awt.Dimension(50, 50));
        ExitButton_Homepage_Panel.setPreferredSize(new java.awt.Dimension(50, 50));
        ExitButton_Homepage_Panel.setRequestFocusEnabled(false);
        ExitButton_Homepage_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitButton_Homepage_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitButton_Homepage_PanelMouseExited(evt);
            }
        });
        ExitButton_Homepage_Panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton_Homepage_PanelActionPerformed(evt);
            }
        });

        contentPanel_HomePage_Panel.setBackground(new java.awt.Color(102, 255, 255));

        text_EnDe_Label_Content_Panel_Homepage_Panel.setBackground(new java.awt.Color(102, 255, 255));
        text_EnDe_Label_Content_Panel_Homepage_Panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/text_EnDe.png"))); // NOI18N
        text_EnDe_Label_Content_Panel_Homepage_Panel.setToolTipText("Text Encryption & Decryption\n- use AES Cypher for Encryption of text\n- use AES Cypher for Decryption of Previously Encrypted text, encrypted using SAME cypher");
        text_EnDe_Label_Content_Panel_Homepage_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        text_EnDe_Label_Content_Panel_Homepage_Panel.setOpaque(true);
        text_EnDe_Label_Content_Panel_Homepage_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                text_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                text_EnDe_Label_Content_Panel_Homepage_PanelMouseExited(evt);
            }
        });

        file_EnDe_Label_Content_Panel_Homepage_Panel.setBackground(new java.awt.Color(102, 255, 255));
        file_EnDe_Label_Content_Panel_Homepage_Panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/file_EnDe.png"))); // NOI18N
        file_EnDe_Label_Content_Panel_Homepage_Panel.setToolTipText("File Encryption & Decryption\n- use AES Cypher for Encryption of Selected File\n- use AES Cypher for Decryption of Previously Encrypted File, encrypted using SAME cypher");
        file_EnDe_Label_Content_Panel_Homepage_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        file_EnDe_Label_Content_Panel_Homepage_Panel.setOpaque(true);
        file_EnDe_Label_Content_Panel_Homepage_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                file_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                file_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                file_EnDe_Label_Content_Panel_Homepage_PanelMouseExited(evt);
            }
        });

        image_EnDe_Label_Content_Panel_Homepage_Panel.setBackground(new java.awt.Color(102, 255, 255));
        image_EnDe_Label_Content_Panel_Homepage_Panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/image_EnDe.png"))); // NOI18N
        image_EnDe_Label_Content_Panel_Homepage_Panel.setToolTipText("File Encryption & Decryption\n- view Image\n- use AES Cypher for Encryption of Selected Image\n- use AES Cypher for Decryption of Previously Encrypted Image, encrypted using SAME cypher");
        image_EnDe_Label_Content_Panel_Homepage_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        image_EnDe_Label_Content_Panel_Homepage_Panel.setOpaque(true);
        image_EnDe_Label_Content_Panel_Homepage_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                image_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                image_EnDe_Label_Content_Panel_Homepage_PanelMouseExited(evt);
            }
        });

        visualCryptograpphy_Label_Content_Panel_Homepage_Panel.setBackground(new java.awt.Color(102, 255, 255));
        visualCryptograpphy_Label_Content_Panel_Homepage_Panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/1.png"))); // NOI18N
        visualCryptograpphy_Label_Content_Panel_Homepage_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        visualCryptograpphy_Label_Content_Panel_Homepage_Panel.setOpaque(true);
        visualCryptograpphy_Label_Content_Panel_Homepage_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseExited(evt);
            }
        });

        steganography_Label_Content_Panel_Homepage_Panel.setBackground(new java.awt.Color(102, 255, 255));
        steganography_Label_Content_Panel_Homepage_Panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/1.png"))); // NOI18N
        steganography_Label_Content_Panel_Homepage_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        steganography_Label_Content_Panel_Homepage_Panel.setOpaque(true);
        steganography_Label_Content_Panel_Homepage_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                steganography_Label_Content_Panel_Homepage_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                steganography_Label_Content_Panel_Homepage_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                steganography_Label_Content_Panel_Homepage_PanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contentPanel_HomePage_PanelLayout = new javax.swing.GroupLayout(contentPanel_HomePage_Panel);
        contentPanel_HomePage_Panel.setLayout(contentPanel_HomePage_PanelLayout);
        contentPanel_HomePage_PanelLayout.setHorizontalGroup(
            contentPanel_HomePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel_HomePage_PanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(text_EnDe_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(file_EnDe_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(image_EnDe_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanel_HomePage_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(visualCryptograpphy_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(steganography_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        contentPanel_HomePage_PanelLayout.setVerticalGroup(
            contentPanel_HomePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel_HomePage_PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contentPanel_HomePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(file_EnDe_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image_EnDe_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_EnDe_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPanel_HomePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(steganography_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visualCryptograpphy_Label_Content_Panel_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        bodyPanel_HomePage_Panel.setBackground(new java.awt.Color(0, 12, 52));

        javax.swing.GroupLayout bodyPanel_HomePage_PanelLayout = new javax.swing.GroupLayout(bodyPanel_HomePage_Panel);
        bodyPanel_HomePage_Panel.setLayout(bodyPanel_HomePage_PanelLayout);
        bodyPanel_HomePage_PanelLayout.setHorizontalGroup(
            bodyPanel_HomePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bodyPanel_HomePage_PanelLayout.setVerticalGroup(
            bodyPanel_HomePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout homePage_PanelLayout = new javax.swing.GroupLayout(homePage_Panel);
        homePage_Panel.setLayout(homePage_PanelLayout);
        homePage_PanelLayout.setHorizontalGroup(
            homePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(homePage_PanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cryptFunct_Label_HomePage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(homePage_PanelLayout.createSequentialGroup()
                .addGap(0, 103, Short.MAX_VALUE)
                .addComponent(contentPanel_HomePage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(homePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homePage_PanelLayout.createSequentialGroup()
                    .addComponent(bodyPanel_HomePage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 929, Short.MAX_VALUE)))
        );
        homePage_PanelLayout.setVerticalGroup(
            homePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePage_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cryptFunct_Label_HomePage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton_Homepage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(contentPanel_HomePage_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(homePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bodyPanel_HomePage_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(homePage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(homePage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void steganography_Label_Content_Panel_Homepage_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_steganography_Label_Content_Panel_Homepage_PanelMouseExited
        // TODO add your handling code here:
        steganography_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/1.png")));
    }//GEN-LAST:event_steganography_Label_Content_Panel_Homepage_PanelMouseExited

    private void steganography_Label_Content_Panel_Homepage_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_steganography_Label_Content_Panel_Homepage_PanelMouseEntered
        // TODO add your handling code here:
        steganography_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/steganography_2.png")));
    }//GEN-LAST:event_steganography_Label_Content_Panel_Homepage_PanelMouseEntered

    private void steganography_Label_Content_Panel_Homepage_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_steganography_Label_Content_Panel_Homepage_PanelMouseClicked
        // TODO add your handling code here:

        com.cryptoProject.GUIFrames.SteganographyFrame steganographyFrame = new com.cryptoProject.GUIFrames.SteganographyFrame();
        steganographyFrame.setVisible(true);
        HomeFrame.this.dispose();
    }//GEN-LAST:event_steganography_Label_Content_Panel_Homepage_PanelMouseClicked

    private void visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseExited
        // TODO add your handling code here:
        visualCryptograpphy_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/1.png")));
    }//GEN-LAST:event_visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseExited

    private void visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseEntered
        // TODO add your handling code here:
        visualCryptograpphy_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/visual_2.png")));
    }//GEN-LAST:event_visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseEntered

    private void visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseClicked
        // TODO add your handling code here:

        com.cryptoProject.GUIFrames.VisualCryptographyEncryptFrame visualCryptographyFrame = new com.cryptoProject.GUIFrames.VisualCryptographyEncryptFrame();
        visualCryptographyFrame.setVisible(true);
        HomeFrame.this.dispose();
        
    }//GEN-LAST:event_visualCryptograpphy_Label_Content_Panel_Homepage_PanelMouseClicked

    private void image_EnDe_Label_Content_Panel_Homepage_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image_EnDe_Label_Content_Panel_Homepage_PanelMouseExited
        // TODO add your handling code here:
        image_EnDe_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/image_EnDe.png")));
    }//GEN-LAST:event_image_EnDe_Label_Content_Panel_Homepage_PanelMouseExited

    private void image_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered
        // TODO add your handling code here:
        image_EnDe_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/image_EnDe_2.png")));
    }//GEN-LAST:event_image_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered

    private void image_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked
        // TODO add your handling code here:

        com.cryptoProject.GUIFrames.ImageEnFrame imageEnFrame = new com.cryptoProject.GUIFrames.ImageEnFrame();
        imageEnFrame.setVisible(true);
        HomeFrame.this.dispose();
    }//GEN-LAST:event_image_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked

    private void file_EnDe_Label_Content_Panel_Homepage_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_file_EnDe_Label_Content_Panel_Homepage_PanelMouseExited
        // TODO add your handling code here:
        file_EnDe_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/file_EnDe.png")));
    }//GEN-LAST:event_file_EnDe_Label_Content_Panel_Homepage_PanelMouseExited

    private void file_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_file_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered
        // TODO add your handling code here:
        file_EnDe_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/file_EnDe_2.png")));
    }//GEN-LAST:event_file_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered

    private void file_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_file_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked
        // TODO add your handling code here:
        com.cryptoProject.GUIFrames.FileEnFrame fileEnFrame = new com.cryptoProject.GUIFrames.FileEnFrame();
        fileEnFrame.setVisible(true);
        HomeFrame.this.dispose();
    }//GEN-LAST:event_file_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked

    private void text_EnDe_Label_Content_Panel_Homepage_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_EnDe_Label_Content_Panel_Homepage_PanelMouseExited
        // TODO add your handling code here:
        text_EnDe_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/text_EnDe.png")));
    }//GEN-LAST:event_text_EnDe_Label_Content_Panel_Homepage_PanelMouseExited

    private void text_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered
        // TODO add your handling code here:
        text_EnDe_Label_Content_Panel_Homepage_Panel.setIcon( new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/text_EnDe_2.png")));
    }//GEN-LAST:event_text_EnDe_Label_Content_Panel_Homepage_PanelMouseEntered

    private void text_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked
        // TODO add your handling code here:
        com.cryptoProject.GUIFrames.TextEnFrame textEnDeFrame = new com.cryptoProject.GUIFrames.TextEnFrame();
        textEnDeFrame.setVisible(true);
        HomeFrame.this.dispose();
    }//GEN-LAST:event_text_EnDe_Label_Content_Panel_Homepage_PanelMouseClicked

    private void ExitButton_Homepage_PanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton_Homepage_PanelActionPerformed
        // TODO add your handling code here:g
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/Cross_gray.png"));
        int res = javax.swing.JOptionPane.showConfirmDialog(null, "Do you want to Exit ? ", "ALERT !!!", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon);
        if(res == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitButton_Homepage_PanelActionPerformed

    private void ExitButton_Homepage_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButton_Homepage_PanelMouseEntered
        // TODO add your handling code here:
        if( ExitButton_Homepage_Panel.isEnabled() ) {
            ExitButton_Homepage_Panel.setBorderPainted(true);
        }
    }//GEN-LAST:event_ExitButton_Homepage_PanelMouseEntered

    private void ExitButton_Homepage_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButton_Homepage_PanelMouseExited
        // TODO add your handling code here:
        if( ExitButton_Homepage_Panel.isEnabled() ) {
            ExitButton_Homepage_Panel.setBorderPainted(false);
        }
    }//GEN-LAST:event_ExitButton_Homepage_PanelMouseExited


  /* *
     * //<editor-fold defaultstate="collapsed" desc=" Main meathod ">
        public static void main(String args[]) {
        
        // Look & Feel setting code 
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(FileEnDeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(FileEnDeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(FileEnDeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(FileEnDeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
           }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new HomeFrame().setVisible(true);
                }
            });
        }
        * 
        * */
//</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton_Homepage_Panel;
    private javax.swing.JPanel bodyPanel_HomePage_Panel;
    private javax.swing.JPanel contentPanel_HomePage_Panel;
    private javax.swing.JLabel cryptFunct_Label_HomePage_Panel;
    private javax.swing.JLabel file_EnDe_Label_Content_Panel_Homepage_Panel;
    private javax.swing.JPanel homePage_Panel;
    private javax.swing.JLabel image_EnDe_Label_Content_Panel_Homepage_Panel;
    private javax.swing.JLabel steganography_Label_Content_Panel_Homepage_Panel;
    private javax.swing.JLabel text_EnDe_Label_Content_Panel_Homepage_Panel;
    private javax.swing.JLabel visualCryptograpphy_Label_Content_Panel_Homepage_Panel;
    // End of variables declaration//GEN-END:variables
}
